Task 3.1 burusov
Naberno/Java_OOP pull request #6
Opened 2023-11-13 18:12 UTC by Naberno

Добавлен тест для проверки ответов пользователей в режиме загадок

2023-11-13 19:30 UTC, vpyzhyanov requested changes

2023-11-13 19:30 UTC, vpyzhyanov commented on src/main/java/org/example/MessageHandling.java
> +    public void setPuzzleGame(PuzzleGame puzzleGame) {
1. Метод используете только для теста, значит область видимости у него должна быть минимально допустимая, т.е. package-private
2. Этот сеттер вообще не нужен, т.к. мы заполнить это поле в конструкторе. 
3. Этот сеттер нарушает инкапсуляцию и позволяет всем кому не лень изменять ваш PuzzleGame

2023-11-13 19:30 UTC, vpyzhyanov commented on src/test/java/org/example/BotTest.java
> +                .thenReturn("Верно! Следующая загадка: " + question);
PuzzleGame - простой Java класс, следовательно нет никакой необходимости использовать для него Mockito.

Похоже вы не поняли суть замечания про отсутствие тестов. Раз вы начали играть в такую игру (с использованием Mockito, непонятно зачем), то замечание трансформируется в такое: `Нет тестов на PuzzleGame`

А теперь выбирайте что исправлять)

2023-11-13 19:30 UTC, vpyzhyanov commented on src/test/java/org/example/BotTest.java
> +                .thenReturn("Верно! Следующая загадка: " + question);
Чтобы было совсем понятно покажу на скриншоте что тестирует ваш тест:
![image](https://github.com/Naberno/Java_OOP/assets/71599019/2abb5903-d651-46d7-baff-5f3f1fa6b53f)
Но не вижу ни одной проверки, которая бы проверила puzzleMode

Вывод: ваш тест абсолютно ничего не тестирует

2023-11-19 13:20 UTC, ICenturioNI commented
Владимир, код одобрен!

2023-11-21 01:39 UTC, merged